/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'date' : Time,
  'note' : string,
  'hatchId' : bigint,
  'eventType' : EventType,
}
export type EventType = { 'nestBoxPlaced' : null } |
  { 'crossingFailed' : null } |
  { 'separation' : null } |
  { 'crossingApproved' : null } |
  { 'crossing' : null } |
  { 'generalNote' : null } |
  { 'delivery' : null };
export interface Hatch {
  'id' : bigint,
  'name' : string,
  'createdDate' : Time,
  'state' : HatchState,
  'eventIds' : Array<bigint>,
}
export type HatchState = { 'nestBoxPlaced' : null } |
  { 'separationDue' : null } |
  { 'crossingApproved' : null } |
  { 'readyForCrossing' : null } |
  { 'complete' : null } |
  { 'crossingRecorded' : null } |
  { 'crossingCheckDue' : null } |
  { 'awaitingDelivery' : null } |
  { 'nestBoxDue' : null };
export type Time = bigint;
export interface _SERVICE {
  'addEvent' : ActorMethod<[bigint, EventType, Time, string], bigint>,
  'addHatch' : ActorMethod<[string], bigint>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteHatch' : ActorMethod<[bigint], undefined>,
  'getAllHatches' : ActorMethod<[], Array<Hatch>>,
  'getEventsForHatch' : ActorMethod<[bigint], Array<Event>>,
  'getHatch' : ActorMethod<[bigint], Hatch>,
  'getNotificationBuckets' : ActorMethod<
    [],
    {
      'separationDue' : Array<bigint>,
      'readyForCrossing' : Array<bigint>,
      'crossingCheckDue' : Array<bigint>,
      'nestBoxDue' : Array<bigint>,
    }
  >,
  'updateHatchState' : ActorMethod<[bigint, HatchState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];