/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventType = IDL.Variant({
  'nestBoxPlaced' : IDL.Null,
  'crossingFailed' : IDL.Null,
  'separation' : IDL.Null,
  'crossingApproved' : IDL.Null,
  'crossing' : IDL.Null,
  'generalNote' : IDL.Null,
  'delivery' : IDL.Null,
});
export const Time = IDL.Int;
export const HatchState = IDL.Variant({
  'nestBoxPlaced' : IDL.Null,
  'separationDue' : IDL.Null,
  'crossingApproved' : IDL.Null,
  'readyForCrossing' : IDL.Null,
  'complete' : IDL.Null,
  'crossingRecorded' : IDL.Null,
  'crossingCheckDue' : IDL.Null,
  'awaitingDelivery' : IDL.Null,
  'nestBoxDue' : IDL.Null,
});
export const Hatch = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdDate' : Time,
  'state' : HatchState,
  'eventIds' : IDL.Vec(IDL.Nat),
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'note' : IDL.Text,
  'hatchId' : IDL.Nat,
  'eventType' : EventType,
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([IDL.Nat, EventType, Time, IDL.Text], [IDL.Nat], []),
  'addHatch' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteHatch' : IDL.Func([IDL.Nat], [], []),
  'getAllHatches' : IDL.Func([], [IDL.Vec(Hatch)], ['query']),
  'getEventsForHatch' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], []),
  'getHatch' : IDL.Func([IDL.Nat], [Hatch], []),
  'getNotificationBuckets' : IDL.Func(
      [],
      [
        IDL.Record({
          'separationDue' : IDL.Vec(IDL.Nat),
          'readyForCrossing' : IDL.Vec(IDL.Nat),
          'crossingCheckDue' : IDL.Vec(IDL.Nat),
          'nestBoxDue' : IDL.Vec(IDL.Nat),
        }),
      ],
      ['query'],
    ),
  'updateHatchState' : IDL.Func([IDL.Nat, HatchState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventType = IDL.Variant({
    'nestBoxPlaced' : IDL.Null,
    'crossingFailed' : IDL.Null,
    'separation' : IDL.Null,
    'crossingApproved' : IDL.Null,
    'crossing' : IDL.Null,
    'generalNote' : IDL.Null,
    'delivery' : IDL.Null,
  });
  const Time = IDL.Int;
  const HatchState = IDL.Variant({
    'nestBoxPlaced' : IDL.Null,
    'separationDue' : IDL.Null,
    'crossingApproved' : IDL.Null,
    'readyForCrossing' : IDL.Null,
    'complete' : IDL.Null,
    'crossingRecorded' : IDL.Null,
    'crossingCheckDue' : IDL.Null,
    'awaitingDelivery' : IDL.Null,
    'nestBoxDue' : IDL.Null,
  });
  const Hatch = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdDate' : Time,
    'state' : HatchState,
    'eventIds' : IDL.Vec(IDL.Nat),
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'note' : IDL.Text,
    'hatchId' : IDL.Nat,
    'eventType' : EventType,
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([IDL.Nat, EventType, Time, IDL.Text], [IDL.Nat], []),
    'addHatch' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteHatch' : IDL.Func([IDL.Nat], [], []),
    'getAllHatches' : IDL.Func([], [IDL.Vec(Hatch)], ['query']),
    'getEventsForHatch' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], []),
    'getHatch' : IDL.Func([IDL.Nat], [Hatch], []),
    'getNotificationBuckets' : IDL.Func(
        [],
        [
          IDL.Record({
            'separationDue' : IDL.Vec(IDL.Nat),
            'readyForCrossing' : IDL.Vec(IDL.Nat),
            'crossingCheckDue' : IDL.Vec(IDL.Nat),
            'nestBoxDue' : IDL.Vec(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'updateHatchState' : IDL.Func([IDL.Nat, HatchState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };