/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Hatch {
    id: bigint;
    name: string;
    createdDate: Time;
    state: HatchState;
    eventIds: Array<bigint>;
}
export type Time = bigint;
export interface Event {
    id: bigint;
    date: Time;
    note: string;
    hatchId: bigint;
    eventType: EventType;
}
export enum EventType {
    nestBoxPlaced = "nestBoxPlaced",
    crossingFailed = "crossingFailed",
    separation = "separation",
    crossingApproved = "crossingApproved",
    crossing = "crossing",
    generalNote = "generalNote",
    delivery = "delivery"
}
export enum HatchState {
    nestBoxPlaced = "nestBoxPlaced",
    separationDue = "separationDue",
    crossingApproved = "crossingApproved",
    readyForCrossing = "readyForCrossing",
    complete = "complete",
    crossingRecorded = "crossingRecorded",
    crossingCheckDue = "crossingCheckDue",
    awaitingDelivery = "awaitingDelivery",
    nestBoxDue = "nestBoxDue"
}
export interface backendInterface {
    addEvent(hatchId: bigint, eventType: EventType, date: Time, note: string): Promise<bigint>;
    addHatch(name: string): Promise<bigint>;
    deleteEvent(eventId: bigint): Promise<void>;
    deleteHatch(hatchId: bigint): Promise<void>;
    getAllHatches(): Promise<Array<Hatch>>;
    getEventsForHatch(hatchId: bigint): Promise<Array<Event>>;
    getHatch(hatchId: bigint): Promise<Hatch>;
    getNotificationBuckets(): Promise<{
        separationDue: Array<bigint>;
        readyForCrossing: Array<bigint>;
        crossingCheckDue: Array<bigint>;
        nestBoxDue: Array<bigint>;
    }>;
    updateHatchState(hatchId: bigint, newState: HatchState): Promise<void>;
}
import type { Event as _Event, EventType as _EventType, Hatch as _Hatch, HatchState as _HatchState, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEvent(arg0: bigint, arg1: EventType, arg2: Time, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addHatch(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHatch(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteHatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHatch(arg0);
            return result;
        }
    }
    async getAllHatches(): Promise<Array<Hatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHatches();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHatches();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsForHatch(arg0: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsForHatch(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsForHatch(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHatch(arg0: bigint): Promise<Hatch> {
        if (this.processError) {
            try {
                const result = await this.actor.getHatch(arg0);
                return from_candid_Hatch_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHatch(arg0);
            return from_candid_Hatch_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationBuckets(): Promise<{
        separationDue: Array<bigint>;
        readyForCrossing: Array<bigint>;
        crossingCheckDue: Array<bigint>;
        nestBoxDue: Array<bigint>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationBuckets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationBuckets();
            return result;
        }
    }
    async updateHatchState(arg0: bigint, arg1: HatchState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHatchState(arg0, to_candid_HatchState_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHatchState(arg0, to_candid_HatchState_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EventType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_HatchState_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HatchState): HatchState {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Hatch_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hatch): Hatch {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    note: string;
    hatchId: bigint;
    eventType: _EventType;
}): {
    id: bigint;
    date: Time;
    note: string;
    hatchId: bigint;
    eventType: EventType;
} {
    return {
        id: value.id,
        date: value.date,
        note: value.note,
        hatchId: value.hatchId,
        eventType: from_candid_EventType_n11(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdDate: _Time;
    state: _HatchState;
    eventIds: Array<bigint>;
}): {
    id: bigint;
    name: string;
    createdDate: Time;
    state: HatchState;
    eventIds: Array<bigint>;
} {
    return {
        id: value.id,
        name: value.name,
        createdDate: value.createdDate,
        state: from_candid_HatchState_n6(_uploadFile, _downloadFile, value.state),
        eventIds: value.eventIds
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nestBoxPlaced: null;
} | {
    crossingFailed: null;
} | {
    separation: null;
} | {
    crossingApproved: null;
} | {
    crossing: null;
} | {
    generalNote: null;
} | {
    delivery: null;
}): EventType {
    return "nestBoxPlaced" in value ? EventType.nestBoxPlaced : "crossingFailed" in value ? EventType.crossingFailed : "separation" in value ? EventType.separation : "crossingApproved" in value ? EventType.crossingApproved : "crossing" in value ? EventType.crossing : "generalNote" in value ? EventType.generalNote : "delivery" in value ? EventType.delivery : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nestBoxPlaced: null;
} | {
    separationDue: null;
} | {
    crossingApproved: null;
} | {
    readyForCrossing: null;
} | {
    complete: null;
} | {
    crossingRecorded: null;
} | {
    crossingCheckDue: null;
} | {
    awaitingDelivery: null;
} | {
    nestBoxDue: null;
}): HatchState {
    return "nestBoxPlaced" in value ? HatchState.nestBoxPlaced : "separationDue" in value ? HatchState.separationDue : "crossingApproved" in value ? HatchState.crossingApproved : "readyForCrossing" in value ? HatchState.readyForCrossing : "complete" in value ? HatchState.complete : "crossingRecorded" in value ? HatchState.crossingRecorded : "crossingCheckDue" in value ? HatchState.crossingCheckDue : "awaitingDelivery" in value ? HatchState.awaitingDelivery : "nestBoxDue" in value ? HatchState.nestBoxDue : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hatch>): Array<Hatch> {
    return value.map((x)=>from_candid_Hatch_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n9(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_HatchState_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HatchState): _HatchState {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HatchState): {
    nestBoxPlaced: null;
} | {
    separationDue: null;
} | {
    crossingApproved: null;
} | {
    readyForCrossing: null;
} | {
    complete: null;
} | {
    crossingRecorded: null;
} | {
    crossingCheckDue: null;
} | {
    awaitingDelivery: null;
} | {
    nestBoxDue: null;
} {
    return value == HatchState.nestBoxPlaced ? {
        nestBoxPlaced: null
    } : value == HatchState.separationDue ? {
        separationDue: null
    } : value == HatchState.crossingApproved ? {
        crossingApproved: null
    } : value == HatchState.readyForCrossing ? {
        readyForCrossing: null
    } : value == HatchState.complete ? {
        complete: null
    } : value == HatchState.crossingRecorded ? {
        crossingRecorded: null
    } : value == HatchState.crossingCheckDue ? {
        crossingCheckDue: null
    } : value == HatchState.awaitingDelivery ? {
        awaitingDelivery: null
    } : value == HatchState.nestBoxDue ? {
        nestBoxDue: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    nestBoxPlaced: null;
} | {
    crossingFailed: null;
} | {
    separation: null;
} | {
    crossingApproved: null;
} | {
    crossing: null;
} | {
    generalNote: null;
} | {
    delivery: null;
} {
    return value == EventType.nestBoxPlaced ? {
        nestBoxPlaced: null
    } : value == EventType.crossingFailed ? {
        crossingFailed: null
    } : value == EventType.separation ? {
        separation: null
    } : value == EventType.crossingApproved ? {
        crossingApproved: null
    } : value == EventType.crossing ? {
        crossing: null
    } : value == EventType.generalNote ? {
        generalNote: null
    } : value == EventType.delivery ? {
        delivery: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
